import { RealEstate } from "@/src/shared/api/types";

export const realEstateData: RealEstate[] = [
  {
    id: '1',
    title: 'Современная квартира в центре Бангкока',
    description: 'Просторная квартира с видом на город, полностью меблированная',
    price: 15000000,
    area: 85,
    bedrooms: 2,
    bathrooms: 2,
    location: 'Бангкок, Силом',
    image: '/placeholder-apartment.jpg',
  },
  {
    id: '2',
    title: 'Вилла с бассейном на Пхукете',
    description: 'Роскошная вилла с частным бассейном и выходом к пляжу',
    price: 45000000,
    area: 350,
    bedrooms: 4,
    bathrooms: 3,
    location: 'Пхукет, Ката',
    image: '/placeholder-villa.jpg',
  },
  {
    id: '3',
    title: 'Кондо в Паттайе',
    description: 'Уютная квартира в новом жилом комплексе',
    price: 7500000,
    area: 45,
    bedrooms: 1,
    bathrooms: 1,
    location: 'Паттайя, Центр',
    image: '/placeholder-condo.jpg',
  },
  {
    id: '4',
    title: 'Таунхаус в Чиангмае',
    description: 'Традиционный таунхаус в старом городе',
    price: 12000000,
    area: 180,
    bedrooms: 3,
    bathrooms: 2,
    location: 'Чиангмай, Старый город',
    image: '/placeholder-townhouse.jpg',
  },
  {
    id: '5',
    title: 'Пентхаус с панорамным видом',
    description: 'Элитный пентхаус на верхнем этаже небоскреба',
    price: 85000000,
    area: 320,
    bedrooms: 3,
    bathrooms: 3,
    location: 'Бангкок, Сукхумвит',
    image: '/placeholder-penthouse.jpg',
  },
  {
    id: '6',
    title: 'Бунгало на Самуи',
    description: 'Уединенное бунгало в тропическом саду',
    price: 28000000,
    area: 200,
    bedrooms: 2,
    bathrooms: 2,
    location: 'Самуи, Чавенг',
    image: '/placeholder-bungalow.jpg',
  },
  {
    id: '7',
    title: 'Офисное помещение в деловом районе',
    description: 'Современное офисное пространство',
    price: 25000000,
    area: 150,
    bedrooms: 0,
    bathrooms: 2,
    location: 'Бангкок, Асок',
    image: '/placeholder-office.jpg',
  },
    {
    id: '8',
    title: 'Апартаменты на берегу моря в Хуахине',
    description: 'Апартаменты класса люкс с видом на Сиамский залив',
    price: 32000000,
    area: 110,
    bedrooms: 2,
    bathrooms: 2,
    location: 'Хуахин, Пляж',
    image: '/placeholder-beach-apartment.jpg',
  },
  {
    id: '9',
    title: 'Коммерческая недвижимость в Бангкоке',
    description: 'Готовый бизнес в торговом центре',
    price: 68000000,
    area: 280,
    bedrooms: 0,
    bathrooms: 3,
    location: 'Бангкок, Пратунам',
    image: '/placeholder-commercial.jpg',
  }
];